apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-recon
  labels:
    app.kubernetes.io/name: ozone
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: recon
spec:
  type: {{ .Values.reconService.type }}
  ports:
    - name: http
      port: 9888
      targetPort: http
      {{- if eq .Values.reconService.type "NodePort" }}
      nodePort: {{ .Values.reconService.nodePort }}
      {{- end }}
  selector:
    app.kubernetes.io/name: ozone
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: recon
