apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-scm
  labels:
    app.kubernetes.io/name: ozone
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: scm
spec:
  clusterIP: None
  ports:
    - name: rpc
      port: 9860
    - name: http
      port: 9876
  selector:
    app.kubernetes.io/name: ozone
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: scm
