#!/usr/bin/env bash
# Generate a registry-swapped values file for charts/bdp.
#
# The canonical charts/bdp/values.yaml pins every image (the bdp/* platform
# images AND the mirrored tools/* images referenced by the vendored subcharts)
# to the marketplace ACR by sha256 digest. Because mirroring between registries
# is done with `crane cp` (digest-preserving — see scripts/mirror-tools.sh and
# scripts/release.sh), the SAME digests are valid in any mirror; only the
# registry prefix differs. This script therefore derives a complete values
# file from the canonical one by swapping the registry on every reference at
# once — it cannot miss a key, because it never enumerates them.
#
# It also sets global.airgapRegistry to the target, so runtime tool installs
# (bdp-service-manager pulling oci://<registry>/charts/* and rewriting tool
# images to <registry>/tools/*) resolve from the same mirror.
#
# Usage: gen-registry-values.sh <registry> [outfile]
#   e.g. gen-registry-values.sh ghcr.io/bluechiptech charts/bdp/values-ghcr.yaml
#   Install with:  helm install bdp charts/bdp -f <outfile> ...
set -euo pipefail

REG="${1:?usage: gen-registry-values.sh <registry> [outfile]  e.g. ghcr.io/bluechiptech}"
OUT="${2:-/dev/stdout}"
HERE="$(cd "$(dirname "$0")" && pwd)"
SRC="$HERE/../charts/bdp/values.yaml"
ACR_HOST="bdpmarketplace.azurecr.io"

{
  echo "# GENERATED by scripts/gen-registry-values.sh $REG — do not edit by hand."
  echo "# Derived from charts/bdp/values.yaml with every image registry swapped to"
  echo "# $REG (digests unchanged: mirrors are digest-preserving crane copies) and"
  echo "# global.airgapRegistry set so runtime tool installs resolve there too."
  sed -e "s|${ACR_HOST//./\\.}|$REG|g" \
      -e "s|^  airgapRegistry: \"\"|  airgapRegistry: \"$REG\"|" \
      "$SRC"
} > "$OUT"
